package models

import (
	"superapps/entities"
)

type ContentApplicationResponse entities.ContentApplicationResponse
type AllCountContent entities.AllCountContent
type Content entities.Content
type ContentComment entities.ContentComment
type ContentCommentUser entities.ContentCommentUser
type ContentCommentResponse entities.ContentCommentResponse
type ContentCommentUserResponse entities.ContentCommentUserResponse
type ContentLike entities.ContentLike
type ContentLikeUser entities.ContentLikeUser
type ContentLikeResponse entities.ContentLikeResponse
type ContentLikeUserResponse entities.ContentLikeUserResponse
type ContentMedia entities.ContentMedia
type ContentResponse entities.ContentResponse
type ContentMediaResponse entities.ContentMediaResponse
type ContentUser entities.ContentUser
type ContentUserResponse entities.ContentUserResponse